/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HubIndexRouteImport } from './routes/hub/index'
import { Route as HubServicesRouteImport } from './routes/hub/services'
import { Route as HubDirectionRouteImport } from './routes/hub/direction'
import { Route as HubContractRouteImport } from './routes/hub/contract'
import { Route as HubDocsSlugRouteImport } from './routes/hub/docs.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/hub/',
  path: '/hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubServicesRoute = HubServicesRouteImport.update({
  id: '/hub/services',
  path: '/hub/services',
  getParentRoute: () => rootRouteImport,
} as any)
const HubDirectionRoute = HubDirectionRouteImport.update({
  id: '/hub/direction',
  path: '/hub/direction',
  getParentRoute: () => rootRouteImport,
} as any)
const HubContractRoute = HubContractRouteImport.update({
  id: '/hub/contract',
  path: '/hub/contract',
  getParentRoute: () => rootRouteImport,
} as any)
const HubDocsSlugRoute = HubDocsSlugRouteImport.update({
  id: '/hub/docs/$slug',
  path: '/hub/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hub/contract': typeof HubContractRoute
  '/hub/direction': typeof HubDirectionRoute
  '/hub/services': typeof HubServicesRoute
  '/hub/': typeof HubIndexRoute
  '/hub/docs/$slug': typeof HubDocsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hub/contract': typeof HubContractRoute
  '/hub/direction': typeof HubDirectionRoute
  '/hub/services': typeof HubServicesRoute
  '/hub': typeof HubIndexRoute
  '/hub/docs/$slug': typeof HubDocsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hub/contract': typeof HubContractRoute
  '/hub/direction': typeof HubDirectionRoute
  '/hub/services': typeof HubServicesRoute
  '/hub/': typeof HubIndexRoute
  '/hub/docs/$slug': typeof HubDocsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hub/contract'
    | '/hub/direction'
    | '/hub/services'
    | '/hub/'
    | '/hub/docs/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hub/contract'
    | '/hub/direction'
    | '/hub/services'
    | '/hub'
    | '/hub/docs/$slug'
  id:
    | '__root__'
    | '/'
    | '/hub/contract'
    | '/hub/direction'
    | '/hub/services'
    | '/hub/'
    | '/hub/docs/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HubContractRoute: typeof HubContractRoute
  HubDirectionRoute: typeof HubDirectionRoute
  HubServicesRoute: typeof HubServicesRoute
  HubIndexRoute: typeof HubIndexRoute
  HubDocsSlugRoute: typeof HubDocsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/': {
      id: '/hub/'
      path: '/hub'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/services': {
      id: '/hub/services'
      path: '/hub/services'
      fullPath: '/hub/services'
      preLoaderRoute: typeof HubServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/direction': {
      id: '/hub/direction'
      path: '/hub/direction'
      fullPath: '/hub/direction'
      preLoaderRoute: typeof HubDirectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/contract': {
      id: '/hub/contract'
      path: '/hub/contract'
      fullPath: '/hub/contract'
      preLoaderRoute: typeof HubContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/docs/$slug': {
      id: '/hub/docs/$slug'
      path: '/hub/docs/$slug'
      fullPath: '/hub/docs/$slug'
      preLoaderRoute: typeof HubDocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HubContractRoute: HubContractRoute,
  HubDirectionRoute: HubDirectionRoute,
  HubServicesRoute: HubServicesRoute,
  HubIndexRoute: HubIndexRoute,
  HubDocsSlugRoute: HubDocsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
